[package]
name = "your_package_name"  # Replace with your actual package name
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
mysql = "20.0.0"

